version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2.7-jessie

    steps:
      - checkout
      # Download and cache python dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run: nosetest

workflows:
  version: 2
  run_test:
    jobs:
      - test:
        filters:
          branches:
            only: /.*/
    context: org-global
